// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxzqhtnwltuzqvpgqbyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4enFodG53bHR1enF2cGdxYnlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyODczOTgsImV4cCI6MjA2MDg2MzM5OH0.y5Uw2AnV-4i9l3X9D5IAd8oMARcaTw1mcyNSV0fPPV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);